remote_theme: samarsault/plainwhite-jekyll

title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: # this means to ignore newlines until "show_exerpts:"
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Marcelo Falchetti
  tagline: 
  date_format: "%b %-d, %Y"
  sitemap: true 
  search: true 
  dark_mode: true 
  portfolio_image: "imagens/circle-cropped.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  # generate social links in footer
  social_links:
    twitter: userfalchetti
    github:  mfalchetti
    linkedIn: in/marcelo-falchetti/

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
